name: Build
on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Game Package Name (e.g., com.dts.freefireth or com.dts.freefiremax)"
        required: true
        default: "com.dts.freefireth"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'gradle'

    - name: Prepare and Build Module
      run: |
        chmod +x ./gradlew
        # Inject the package name into the C++ header file
        sed -i "s/com.game.packagename/${{ github.event.inputs.package_name }}/g" module/src/main/cpp/game.h
        # Add the package name to the module description for visibility in Magisk
        sed -i 's/moduleDescription = "/moduleDescription = "(${{ github.event.inputs.package_name }}) /g' module.gradle
        # Run the build
        ./gradlew :module:assembleRelease

    - name: Upload Magisk Module
      uses: actions/upload-artifact@v4
      with:
        name: zygisk-il2cppdumper-${{ github.event.inputs.package_name }}
        path: out/*
